export const accountTemplates = [
  // ============================================================
  // ASSETS
  // ============================================================

  {
    code: "AST-001",
    name: "Cash",
    type: "asset",
    category: "current_asset",
    subCategory: "cash_and_cash_equivalents",
    normalBalance: "debit",
    description: "Physical cash held by the business",
  },
  {
    code: "AST-002",
    name: "Petty Cash",
    type: "asset",
    category: "current_asset",
    subCategory: "cash_and_cash_equivalents",
    normalBalance: "debit",
    description: "Small amount of cash maintained for minor expenses",
  },
  {
    code: "AST-003",
    name: "Bank Account",
    type: "asset",
    category: "current_asset",
    subCategory: "cash_and_cash_equivalents",
    normalBalance: "debit",
    description: "Business bank account",
  },
  {
    code: "AST-004",
    name: "Savings Account",
    type: "asset",
    category: "current_asset",
    subCategory: "cash_and_cash_equivalents",
    normalBalance: "debit",
    description: "Business savings bank account",
  },
  {
    code: "AST-005",
    name: "Current Account",
    type: "asset",
    category: "current_asset",
    subCategory: "cash_and_cash_equivalents",
    normalBalance: "debit",
    description: "Business current bank account",
  },
  {
    code: "AST-006",
    name: "Accounts Receivable",
    type: "asset",
    category: "current_asset",
    subCategory: "receivables",
    normalBalance: "debit",
    description: "Money owed to the business by customers",
  },
  {
    code: "AST-007",
    name: "Inventory",
    type: "asset",
    category: "current_asset",
    subCategory: "inventory",
    normalBalance: "debit",
    description: "Goods held for resale",
  },
  {
    code: "AST-008",
    name: "Raw Materials Inventory",
    type: "asset",
    category: "current_asset",
    subCategory: "inventory",
    normalBalance: "debit",
    description: "Raw materials held for production",
  },
  {
    code: "AST-009",
    name: "Finished Goods Inventory",
    type: "asset",
    category: "current_asset",
    subCategory: "inventory",
    normalBalance: "debit",
    description: "Completed goods held for sale",
  },
  {
    code: "AST-010",
    name: "Prepaid Expenses",
    type: "asset",
    category: "current_asset",
    subCategory: "prepayments",
    normalBalance: "debit",
    description: "Expenses paid in advance",
  },
  {
    code: "AST-011",
    name: "Security Deposit",
    type: "asset",
    category: "current_asset",
    subCategory: "deposits",
    normalBalance: "debit",
    description: "Refundable deposits paid by the business",
  },
  {
    code: "AST-012",
    name: "Equipment",
    type: "asset",
    category: "fixed_asset",
    subCategory: "property_plant_equipment",
    normalBalance: "debit",
    description: "Business equipment",
  },
  {
    code: "AST-013",
    name: "Computer Equipment",
    type: "asset",
    category: "fixed_asset",
    subCategory: "property_plant_equipment",
    normalBalance: "debit",
    description: "Computers and related equipment",
  },
  {
    code: "AST-014",
    name: "Furniture and Fixtures",
    type: "asset",
    category: "fixed_asset",
    subCategory: "property_plant_equipment",
    normalBalance: "debit",
    description: "Furniture and fixtures used by the business",
  },
  {
    code: "AST-015",
    name: "Vehicles",
    type: "asset",
    category: "fixed_asset",
    subCategory: "property_plant_equipment",
    normalBalance: "debit",
    description: "Vehicles owned by the business",
  },
  {
    code: "AST-016",
    name: "Machinery",
    type: "asset",
    category: "fixed_asset",
    subCategory: "property_plant_equipment",
    normalBalance: "debit",
    description: "Business machinery",
  },
  {
    code: "AST-017",
    name: "Buildings",
    type: "asset",
    category: "fixed_asset",
    subCategory: "property_plant_equipment",
    normalBalance: "debit",
    description: "Buildings owned by the business",
  },
  {
    code: "AST-018",
    name: "Land",
    type: "asset",
    category: "fixed_asset",
    subCategory: "property_plant_equipment",
    normalBalance: "debit",
    description: "Land owned by the business",
  },
  {
    code: "AST-019",
    name: "Accumulated Depreciation",
    type: "asset",
    category: "contra_asset",
    subCategory: "accumulated_depreciation",
    normalBalance: "credit",
    description: "Accumulated depreciation of fixed assets",
  },
  {
    code: "AST-020",
    name: "Bank",
    type: "asset",
    category: "current_asset",
    subCategory: "cash_and_bank",
    normalBalance: "debit",
    description: "Bank account used for business transactions",
  },

  // ============================================================
  // LIABILITIES
  // ============================================================

  {
    code: "LIA-001",
    name: "Accounts Payable",
    type: "liability",
    category: "current_liability",
    subCategory: "payables",
    normalBalance: "credit",
    description: "Money owed to suppliers and vendors",
  },
  {
    code: "LIA-002",
    name: "Short Term Loan",
    type: "liability",
    category: "current_liability",
    subCategory: "loans",
    normalBalance: "credit",
    description: "Loans payable within a short period",
  },
  {
    code: "LIA-003",
    name: "Long Term Loan",
    type: "liability",
    category: "long_term_liability",
    subCategory: "loans",
    normalBalance: "credit",
    description: "Long-term business loans",
  },
  {
    code: "LIA-004",
    name: "Bank Loan",
    type: "liability",
    category: "liability",
    subCategory: "loans",
    normalBalance: "credit",
    description: "Loan obtained from a bank",
  },
  {
    code: "LIA-005",
    name: "Credit Card Payable",
    type: "liability",
    category: "current_liability",
    subCategory: "payables",
    normalBalance: "credit",
    description: "Outstanding credit card balance",
  },
  {
    code: "LIA-006",
    name: "Salary Payable",
    type: "liability",
    category: "current_liability",
    subCategory: "accrued_expenses",
    normalBalance: "credit",
    description: "Employee salaries payable",
  },
  {
    code: "LIA-007",
    name: "Rent Payable",
    type: "liability",
    category: "current_liability",
    subCategory: "accrued_expenses",
    normalBalance: "credit",
    description: "Outstanding rent payable",
  },
  {
    code: "LIA-008",
    name: "Tax Payable",
    type: "liability",
    category: "current_liability",
    subCategory: "taxes",
    normalBalance: "credit",
    description: "Taxes payable to government authorities",
  },
  {
    code: "LIA-009",
    name: "GST Payable",
    type: "liability",
    category: "current_liability",
    subCategory: "taxes",
    normalBalance: "credit",
    description: "GST payable",
  },
  {
    code: "LIA-010",
    name: "VAT Payable",
    type: "liability",
    category: "current_liability",
    subCategory: "taxes",
    normalBalance: "credit",
    description: "VAT payable",
  },
  {
    code: "LIA-011",
    name: "Accrued Expenses",
    type: "liability",
    category: "current_liability",
    subCategory: "accrued_expenses",
    normalBalance: "credit",
    description: "Expenses incurred but not yet paid",
  },
  {
    code: "LIA-012",
    name: "Customer Advances",
    type: "liability",
    category: "current_liability",
    subCategory: "customer_advances",
    normalBalance: "credit",
    description: "Advance payments received from customers",
  },

  // ============================================================
  // EQUITY
  // ============================================================

  {
    code: "EQT-001",
    name: "Owner's Capital",
    type: "equity",
    category: "owner_equity",
    subCategory: "capital",
    normalBalance: "credit",
    description: "Capital invested by the owner",
  },
  {
    code: "EQT-002",
    name: "Owner's Drawings",
    type: "equity",
    category: "owner_equity",
    subCategory: "drawings",
    normalBalance: "debit",
    description: "Money or assets withdrawn by the owner",
  },
  {
    code: "EQT-003",
    name: "Retained Earnings",
    type: "equity",
    category: "retained_earnings",
    subCategory: "retained_earnings",
    normalBalance: "credit",
    description: "Accumulated profits retained in the business",
  },
  {
    code: "EQT-004",
    name: "Opening Balance Equity",
    type: "equity",
    category: "opening_balance",
    subCategory: "opening_balance",
    normalBalance: "credit",
    description: "Equity used for opening balances",
  },
  {
    code: "EQT-005",
    name: "Current Year Earnings",
    type: "equity",
    category: "retained_earnings",
    subCategory: "current_year_earnings",
    normalBalance: "credit",
    description: "Profit or loss for the current accounting year",
  },

  // ============================================================
  // INCOME
  // ============================================================

  {
    code: "INC-001",
    name: "Sales",
    type: "income",
    category: "operating_income",
    subCategory: "sales",
    normalBalance: "credit",
    description: "Revenue from sale of goods",
  },
  {
    code: "INC-002",
    name: "Product Sales",
    type: "income",
    category: "operating_income",
    subCategory: "sales",
    normalBalance: "credit",
    description: "Revenue generated from product sales",
  },
  {
    code: "INC-003",
    name: "Service Income",
    type: "income",
    category: "operating_income",
    subCategory: "services",
    normalBalance: "credit",
    description: "Revenue generated from services",
  },
  {
    code: "INC-004",
    name: "Consulting Income",
    type: "income",
    category: "operating_income",
    subCategory: "services",
    normalBalance: "credit",
    description: "Income from consulting services",
  },
  {
    code: "INC-005",
    name: "Commission Income",
    type: "income",
    category: "operating_income",
    subCategory: "commission",
    normalBalance: "credit",
    description: "Income earned from commissions",
  },
  {
    code: "INC-006",
    name: "Rental Income",
    type: "income",
    category: "other_income",
    subCategory: "rental",
    normalBalance: "credit",
    description: "Income earned from renting assets or property",
  },
  {
    code: "INC-007",
    name: "Interest Income",
    type: "income",
    category: "other_income",
    subCategory: "interest",
    normalBalance: "credit",
    description: "Interest earned by the business",
  },
  {
    code: "INC-008",
    name: "Delivery Income",
    type: "income",
    category: "operating_income",
    subCategory: "delivery",
    normalBalance: "credit",
    description: "Income earned from delivery services",
  },
  {
    code: "INC-009",
    name: "Other Operating Income",
    type: "income",
    category: "operating_income",
    subCategory: "other",
    normalBalance: "credit",
    description: "Other income related to normal business operations",
  },
  {
    code: "INC-010",
    name: "Other Income",
    type: "income",
    category: "other_income",
    subCategory: "other",
    normalBalance: "credit",
    description: "Other non-operating income",
  },

  // ============================================================
  // COST OF GOODS SOLD
  // ============================================================

  {
    code: "COG-001",
    name: "Purchases",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "purchases",
    normalBalance: "debit",
    description: "Goods purchased for resale",
  },
  {
    code: "COG-002",
    name: "Purchase Returns",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "purchase_returns",
    normalBalance: "credit",
    description: "Goods returned to suppliers",
  },
  {
    code: "COG-003",
    name: "Raw Material Purchases",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "raw_materials",
    normalBalance: "debit",
    description: "Raw materials purchased for production",
  },
  {
    code: "COG-004",
    name: "Freight Inward",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "freight",
    normalBalance: "debit",
    description: "Transportation costs for purchased goods",
  },
  {
    code: "COG-005",
    name: "Import Duty",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "duties",
    normalBalance: "debit",
    description: "Import duties related to inventory",
  },
  {
    code: "COG-006",
    name: "Direct Labour",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "direct_labour",
    normalBalance: "debit",
    description: "Direct labour costs related to production",
  },
  {
    code: "COG-007",
    name: "Manufacturing Costs",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "manufacturing",
    normalBalance: "debit",
    description: "Direct manufacturing costs",
  },
  {
    code: "COG-008",
    name: "Cost of Goods Sold",
    type: "expense",
    category: "cost_of_goods_sold",
    subCategory: "cogs",
    normalBalance: "debit",
    description: "Cost associated with goods sold",
  },

  // ============================================================
  // OPERATING EXPENSES
  // ============================================================

  {
    code: "EXP-001",
    name: "Rent Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "occupancy",
    normalBalance: "debit",
    description: "Rent paid for business premises",
  },
  {
    code: "EXP-002",
    name: "Electricity Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "utilities",
    normalBalance: "debit",
    description: "Electricity costs",
  },
  {
    code: "EXP-003",
    name: "Water Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "utilities",
    normalBalance: "debit",
    description: "Water utility costs",
  },
  {
    code: "EXP-004",
    name: "Internet Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "utilities",
    normalBalance: "debit",
    description: "Internet service costs",
  },
  {
    code: "EXP-005",
    name: "Telephone Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "communication",
    normalBalance: "debit",
    description: "Telephone and mobile communication costs",
  },
  {
    code: "EXP-006",
    name: "Salary Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "employee_costs",
    normalBalance: "debit",
    description: "Employee salaries",
  },
  {
    code: "EXP-007",
    name: "Wages Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "employee_costs",
    normalBalance: "debit",
    description: "Employee wages",
  },
  {
    code: "EXP-008",
    name: "Employee Benefits",
    type: "expense",
    category: "operating_expense",
    subCategory: "employee_costs",
    normalBalance: "debit",
    description: "Employee benefits and welfare costs",
  },
  {
    code: "EXP-009",
    name: "Insurance Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "insurance",
    normalBalance: "debit",
    description: "Business insurance costs",
  },
  {
    code: "EXP-010",
    name: "Transportation Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "transportation",
    normalBalance: "debit",
    description: "Business transportation costs",
  },
  {
    code: "EXP-011",
    name: "Fuel Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "transportation",
    normalBalance: "debit",
    description: "Fuel costs for business vehicles",
  },
  {
    code: "EXP-012",
    name: "Vehicle Maintenance",
    type: "expense",
    category: "operating_expense",
    subCategory: "maintenance",
    normalBalance: "debit",
    description: "Maintenance costs for business vehicles",
  },
  {
    code: "EXP-013",
    name: "Repairs and Maintenance",
    type: "expense",
    category: "operating_expense",
    subCategory: "maintenance",
    normalBalance: "debit",
    description: "General repair and maintenance costs",
  },
  {
    code: "EXP-014",
    name: "Advertising Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "marketing",
    normalBalance: "debit",
    description: "Advertising costs",
  },
  {
    code: "EXP-015",
    name: "Marketing Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "marketing",
    normalBalance: "debit",
    description: "Marketing and promotional costs",
  },
  {
    code: "EXP-016",
    name: "Printing Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "office",
    normalBalance: "debit",
    description: "Printing costs",
  },
  {
    code: "EXP-017",
    name: "Stationery Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "office",
    normalBalance: "debit",
    description: "Stationery costs",
  },
  {
    code: "EXP-018",
    name: "Office Supplies",
    type: "expense",
    category: "operating_expense",
    subCategory: "office",
    normalBalance: "debit",
    description: "General office supplies",
  },
  {
    code: "EXP-019",
    name: "Packaging Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "packaging",
    normalBalance: "debit",
    description: "Packaging material costs",
  },
  {
    code: "EXP-020",
    name: "Delivery Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "delivery",
    normalBalance: "debit",
    description: "Business delivery costs",
  },
  {
    code: "EXP-021",
    name: "Shipping Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "shipping",
    normalBalance: "debit",
    description: "Shipping costs",
  },
  {
    code: "EXP-022",
    name: "Travel Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "travel",
    normalBalance: "debit",
    description: "Business travel costs",
  },
  {
    code: "EXP-023",
    name: "Accommodation Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "travel",
    normalBalance: "debit",
    description: "Business accommodation costs",
  },
  {
    code: "EXP-024",
    name: "Meals and Entertainment",
    type: "expense",
    category: "operating_expense",
    subCategory: "entertainment",
    normalBalance: "debit",
    description: "Business meals and entertainment",
  },
  {
    code: "EXP-025",
    name: "Bank Charges",
    type: "expense",
    category: "operating_expense",
    subCategory: "banking",
    normalBalance: "debit",
    description: "Bank service charges",
  },
  {
    code: "EXP-026",
    name: "Payment Gateway Fees",
    type: "expense",
    category: "operating_expense",
    subCategory: "payment_processing",
    normalBalance: "debit",
    description: "Payment gateway and transaction fees",
  },
  {
    code: "EXP-027",
    name: "Accounting Fees",
    type: "expense",
    category: "operating_expense",
    subCategory: "professional_services",
    normalBalance: "debit",
    description: "Accounting and bookkeeping fees",
  },
  {
    code: "EXP-028",
    name: "Legal Fees",
    type: "expense",
    category: "operating_expense",
    subCategory: "professional_services",
    normalBalance: "debit",
    description: "Legal service costs",
  },
  {
    code: "EXP-029",
    name: "Professional Fees",
    type: "expense",
    category: "operating_expense",
    subCategory: "professional_services",
    normalBalance: "debit",
    description: "Professional consulting and service fees",
  },
  {
    code: "EXP-030",
    name: "Software Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "technology",
    normalBalance: "debit",
    description: "Software costs",
  },
  {
    code: "EXP-031",
    name: "Subscription Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "technology",
    normalBalance: "debit",
    description: "Business subscriptions",
  },
  {
    code: "EXP-032",
    name: "Website Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "technology",
    normalBalance: "debit",
    description: "Website-related expenses",
  },
  {
    code: "EXP-033",
    name: "Cloud Services Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "technology",
    normalBalance: "debit",
    description: "Cloud hosting and infrastructure costs",
  },
  {
    code: "EXP-034",
    name: "Security Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "security",
    normalBalance: "debit",
    description: "Business security costs",
  },
  {
    code: "EXP-035",
    name: "Cleaning Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "maintenance",
    normalBalance: "debit",
    description: "Cleaning and housekeeping costs",
  },
  {
    code: "EXP-036",
    name: "Depreciation Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "depreciation",
    normalBalance: "debit",
    description: "Depreciation of fixed assets",
  },
  {
    code: "EXP-037",
    name: "Training Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "employee_costs",
    normalBalance: "debit",
    description: "Employee training costs",
  },
  {
    code: "EXP-038",
    name: "Recruitment Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "employee_costs",
    normalBalance: "debit",
    description: "Employee recruitment costs",
  },
  {
    code: "EXP-039",
    name: "License and Permit Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "government_fees",
    normalBalance: "debit",
    description: "Business licenses and permits",
  },
  {
    code: "EXP-040",
    name: "Government Fees",
    type: "expense",
    category: "operating_expense",
    subCategory: "government_fees",
    normalBalance: "debit",
    description: "Government fees and charges",
  },
  {
    code: "EXP-041",
    name: "Taxes and Duties",
    type: "expense",
    category: "operating_expense",
    subCategory: "taxes",
    normalBalance: "debit",
    description: "Business taxes and duties",
  },
  {
    code: "EXP-042",
    name: "Bad Debt Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "bad_debt",
    normalBalance: "debit",
    description: "Losses from uncollectible customer balances",
  },
  {
    code: "EXP-043",
    name: "Interest Expense",
    type: "expense",
    category: "non_operating_expense",
    subCategory: "interest",
    normalBalance: "debit",
    description: "Interest paid on loans and other liabilities",
  },
  {
    code: "EXP-044",
    name: "Miscellaneous Expense",
    type: "expense",
    category: "operating_expense",
    subCategory: "miscellaneous",
    normalBalance: "debit",
    description: "Other legitimate business expenses",
  },
];
